require('../../common/vendor.js');(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["page_add/components/choose-image/choose-image"],{"176b":function(e,n,t){"use strict";t.d(n,"b",(function(){return c})),t.d(n,"c",(function(){return u})),t.d(n,"a",(function(){return o}));var o={uniPopup:function(){return Promise.all([t.e("common/vendor"),t.e("components/uni-popup/uni-popup")]).then(t.bind(null,"1a7d"))}},c=function(){var e=this,n=e.$createElement;e._self._c;e._isMounted||(e.e0=function(n){return e.$refs.popup.close()})},u=[]},4084:function(e,n,t){"use strict";var o=t("f31e"),c=t.n(o);c.a},4811:function(e,n,t){"use strict";t.r(n);var o=t("176b"),c=t("aa73");for(var u in c)["default"].indexOf(u)<0&&function(e){t.d(n,e,(function(){return c[e]}))}(u);t("4084");var i=t("828b"),s=Object(i["a"])(c["default"],o["b"],o["c"],!1,null,null,null,!1,o["a"],void 0);n["default"]=s.exports},"8f55":function(e,n,t){"use strict";(function(e,t){Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var o={name:"choose-image",props:{emitFunc:{type:String,default:""}},data:function(){return{}},methods:{open:function(){this.$refs.popup.open()},close:function(){this.$refs.popup.close()},chooseImage:function(n){var t=this;e.chooseImage({count:1,sourceType:[n],sizeType:["original"],success:function(e){t.$emit("emitfunc",e.tempFiles),t.close()},fail:function(n){console.log(n),"chooseImage:fail cancel"!=n.errMsg&&e.showModal({title:"没有相关权限",content:"请在设置中打开“使用手机相册”“使用相机”的权限",confirmText:"打开设置",success:function(n){n.confirm&&e.openSetting()}})}})},chooseMessageImage:function(){var e=this;t.chooseMessageFile({count:1,type:"image",success:function(n){e.$emit("emitfunc",n.tempFiles),e.close()}})}}};n.default=o}).call(this,t("df3c")["default"],t("3223")["default"])},aa73:function(e,n,t){"use strict";t.r(n);var o=t("8f55"),c=t.n(o);for(var u in o)["default"].indexOf(u)<0&&function(e){t.d(n,e,(function(){return o[e]}))}(u);n["default"]=c.a},f31e:function(e,n,t){}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'page_add/components/choose-image/choose-image-create-component',
    {
        'page_add/components/choose-image/choose-image-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('df3c')['createComponent'](__webpack_require__("4811"))
        })
    },
    [['page_add/components/choose-image/choose-image-create-component']]
]);
